.PHONY: clean All

All:
	@echo "----------Building project:[ ProjectOne - Debug ]----------"
	@cd "ProjectOne" && "$(MAKE)" -f  "ProjectOne.mk"
clean:
	@echo "----------Cleaning project:[ ProjectOne - Debug ]----------"
	@cd "ProjectOne" && "$(MAKE)" -f  "ProjectOne.mk" clean
