.PHONY: clean All

All:
	@echo "----------Building project:[ ProjectTwo - Debug ]----------"
	@cd "ProjectTwo" && "$(MAKE)" -f  "ProjectTwo.mk"
clean:
	@echo "----------Cleaning project:[ ProjectTwo - Debug ]----------"
	@cd "ProjectTwo" && "$(MAKE)" -f  "ProjectTwo.mk" clean
